template: true
valuesFilePath: ./values.yml

resources:
  - name: app_gitrepo
    type: GitRepo
    configuration:
      gitProvider: {{ .Values.gitRepo.gitProvider }}
      path: {{ .Values.gitRepo.path }}
      branches:
        include: {{ .Values.gitRepo.branch }}

  - name: app_image_name
    type: Image
    configuration:
      registry: {{ .Values.appImage.registry }}
      sourceRepository: docker
      imageName: {{ .Values.appImage.registryUrl }}/docker/app
      imageTag: latest

  - name: app_chart
    type: HelmChart
    configuration:
      sourceArtifactory: {{ .Values.appChart.sourceArtifactory }}
      repository: cst-helm
      chart: app
      version: 0.0.0

pipelines:
  - name: docker_ci_pipeline
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: dbp_group
          dockerFileLocation: app
          dockerFileName: Dockerfile
          dockerImageName: {{ .Values.appImage.registryUrl }}/docker/app
          dockerImageTag: 0.0.${run_number}
          integrations:
            - name: {{ .Values.appImage.registry }}
          inputResources:
            - name: app_gitrepo
              trigger: false

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: dbp_group
          targetRepository: {{ .Values.appImage.repoName }}
          integrations:
            - name: {{ .Values.appImage.registry }}
          inputSteps:
            - name: docker_build
          outputResources:
            - name: app_image_name

  - name: helm_blue_green_pipeline
    steps:
      - name: helm_publish
        type: HelmPublish
        configuration:
          helmVersion: 3
          chartPath: "./chart"
          lint: true
          autoPublishBuildInfo: false
          inputResources:
            - name: app_image_name
            - name: app_gitrepo
              trigger: false
          outputResources:
            - name: app_chart
        execution:
          onStart:
            - CHART_VERSION=0.0.$res_app_image_name_imageTag
            - pushd $res_app_gitrepo_resourcePath/chart
            - "sed -ie \"s/^version: .*$/version: $CHART_VERSION/\" Chart.yaml"
            - "sed -ie \"s/^appVersion: .*$/appVersion: $CHART_VERSION/\" Chart.yaml"
            - popd

      - name: helm_blue_green_deploy
        type: HelmBlueGreenDeploy
        configuration:
          helmVersion: 3
          namespace: {{ .Values.runtime.namespace }}
          blueReleaseName: {{ .Values.runtime.blueReleaseName }}
          blueFlags: "--set image.registry='{{ .Values.appImage.registryUrl }}/docker'"
          greenReleaseName: {{ .Values.runtime.greenReleaseName }}
          greenFlags: "--set image.registry='{{ .Values.appImage.registryUrl }}/docker'"
          roleServices:
            - blueReferenceName: {{ .Values.runtime.blueReleaseName }}-app
              greenReferenceName: {{ .Values.runtime.greenReleaseName }}-app
              idleName: {{ .Values.runtime.idleServiceName }}
              liveName: {{ .Values.runtime.liveServiceName }}
          integrations:
            - name: {{ .Values.runtime.k8s_integration }}
          inputResources:
            - name: app_chart

      - name: helm_blue_green_role_switch
        type: HelmBlueGreenRoleSwitch
        configuration:
          deployStep: helm_blue_green_deploy
          integrations:
            - name: {{ .Values.runtime.k8s_integration }}
          inputSteps:
            - name: helm_blue_green_deploy

      - name: helm_blue_green_cleanup
        type: HelmBlueGreenCleanup
        configuration:
          deployStep: helm_blue_green_deploy
          integrations:
            - name: {{ .Values.runtime.k8s_integration }}
          inputSteps:
            - name: helm_blue_green_role_switch

