gitRepo:
  gitProvider: githubInt                              # <-- replace with your GitRepo integration name
  path: stein321/jfrog-pipelines-helm-blue-green-sample  # <-- replace jfrog with your username or org name
  branch: main

appImage:
  registry: entArt
  registryUrl: demo.jfrog-pipelines.com/cst-docker
  repoName: cst-docker

appChart:
  sourceArtifactory: entArt                   # <-- replace with your Artifactory integration name

runtime:
  k8s_integration: coresvc_k8s                             # <-- replace with your Kubernetes integration name
  namespace: coresvc
  blueReleaseName: app-blue
  greenReleaseName: app-green
  idleServiceName: app-idle
  liveServiceName: app


