apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.service.name" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy | quote }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http-app
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePort)) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
    - name: https
      port: {{ .Values.service.portHttps }}
      targetPort: https-app
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePortHttps)) }}
      nodePort: {{ .Values.service.nodePortHttps }}
      {{- end }}
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
    component: {{ include "app.service.name" . }}