gitRepo:
  gitProvider: myGithub                               # <-- replace with your GitRepo integration name
  path: jfrog/jfrog-pipelines-helm-blue-green-sample  # <-- replace jfrog with your username or org name
  branch: main

appImage:
  registry: myArtifactory                             # <-- replace with your Artifactory integration name
  registryUrl: pipelines.jfrog.io                     # <-- replace with the url to your Artifactory environment

appChart:
  sourceArtifactory: myArtifactory                   # <-- replace with your Artifactory integration name

runtime:
  k8s_integration: myKubernates                       # <-- replace with your Kubernetes integration name
  #namespace: pipe-master-pool                                # <-- replace with the name of the Kubernetes namespace where the Helm chart will be deployed
  namespace: pipelines-demo
  blueReleaseName: app-blue
  greenReleaseName: app-green
  idleServiceName: app-idle
  liveServiceName: app


